### ISSUE TITLE
Heroku App Error

### ISSUE THREAD

**Issue by fast-and-curious-1910** [Auto-bot-Channel/Reddit-bot#2]
Visit https://auto-bot-reddit.herokuapp.com/ and you will get this error 

```
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail
```
<img src = https://i.imgur.com/9J4qbEz.png>

**Comment by Auto-bot-Channel** [comment]
Thanks for looking after us, We needed to upgrade the security of the page and hence had to shut down for a while, Please visit the page again it's up and working; Thank-you @fast-and-curious-1910
